### ISSUE TITLE
Learning Outcome nicht mehr als eigenes Aggregate, sondern als Teil von LR

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/coalbase-learning-outcome#15]

**Comment by JannIntveen** [comment]
evtl. Learning Outcome als Value object von Lernraum.

**Comment by stefanbente** [comment]
LO ist aus meiner Sicht definitiv ein Entity - es unterliegt Editing-Lebenszyklen.

**Comment by JannIntveen** [comment]
https://github.com/Archi-Lab/coalbase-documentation/wiki/Beziehung-Lernraum-zu-LearningOutcome
